server:
  port: 8080
jwt:
  token:
    secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: zzalu-buket
    credentials:
      access-key: AKIAXEUXRPXD3GDITUSE
      secret-key: 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
    stack:
      auto: false
sp: ''
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: moona0222@hufs.ac.kr
    password: zzalu_c109!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ssafy
    url: jdbc:mysql://127.0.0.1:3306/ZZALU?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
  kafka:
    bootstrap-servers: 127.0.0.1:9092
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1
    password: 'zzalu_c109!@'

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false